language: node_js
node_js:
  - "0.11"
  - "0.10"

before_script:
  - npm install blanket istanbul coveralls

script:
  - npm test

after_script: NODE_ENV=test istanbul cover mocha --report lcovonly -- -R spec && cat ./coverage/lcov.info | coveralls && rm -rf ./coverage